=== slaurent22/hk-split-maker/src/schema/hollowknight/splits.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://hksplitmaker.com/hollowknight/splits.schema.json",
    "title": "HK Splits",
    "description": "A Hollow Knight LiveSplit Configuration",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "names": {
            "additionalProperties": false,
            "description": "Name overrides for the splits. Map each autosplit id to a string or an array of strings.",
            "type": "object",
            "properties": {}
        },
        "icons": {
            "additionalProperties": false,
            "description": "Icon overrides for the splits. Map each autosplit id to a autosplit id or an array of autosplit ids.",
            "type": "object",
            "properties": {}
        },
        "ordered": {
            "description": "Ordered splits improve performance and are required for certain splits (e.g. KingsPass).",
            "type": "boolean"
        },
        "endTriggeringAutosplit": {
            "description": "Whether to end time at the last autosplit. Set this to false for full-game runs, where time ends on a final cutscene.",
            "type": "boolean"
        },
        "startTriggeringAutosplit": {
            "description": "Autosplit to use to start the timer, rather than starting on new file",
            "enum": []
        },
        "endingSplit": {
            "description": "Info for the last split if it's a game-ending split rather than an autosplit",
            "type": "object",
            "properties": {
                "name": "The name to appear in the LiveSplit UI",
                "icon": "The autosplit name whose icon to use (e.g. RadianceBoss, HollowKnightBoss)"
            }
        },
        "categoryName": {
            "description": "The category name on the associated speedrun.com board.",
            "type": "string"
        },
        "gameName": {
            "description": "The game name on the associated speedrun.com board.",
            "enum": [
                "Hollow Knight",
                "Hollow Knight Category Extensions",
                "Hollow Knight Mods"
            ]
        },
        "variables": {
            "description": "Additional Info",
            "type": "object"
        },
        "pauseOnMainMenu": {
            "description": "Pause on Main Menu (Required false for All Glitches)",
            "type": "boolean"
        },
        "splitIds": {
            "type": "array",
            "items": {
                "oneOf": []
            }
        },
        "offset": {
            "description": "When time should start (formatted like 00:00:00 or 00:00:00.0000000)",
            "type": "string"
        }
    },
    "required": [
        "endTriggeringAutosplit",
        "categoryName",
        "gameName",
        "splitIds"
    ]
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/pop-percent.json
{
    "categoryName": "PoP%",
    "splitIds": [
        "VengefulSpirit",
        "EnterGreenpath",
        "MothwingCloak",
        "BlueLake",
        "DreamNail",
        "ElderHuEssence",
        "MantisClaw",
        "GalienEssence",
        "XeroEssence",
        "GorgeousHusk",
        "LumaflyLantern",
        "SlyKey",
        "CrystalHeart",
        "ShadeSoul",
        "DesolateDive",
        "SoulTyrantEssence",
        "TollBenchBasin",
        "BrokenVessel",
        "MonarchWings",
        "DreamGate",
        "FailedChampionEssence",
        "GorbEssence",
        "NoEyesEssence",
        "WhitePalaceEntry",
        "PathOfPainEntry",
        "PathOfPain"
    ],
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/p3.json
{
    "categoryName": "Pantheon of the Sage",
    "splitIds": [
        "HiveKnightP",
        "ElderHuP",
        "CollectorP",
        "GodTamerP",
        "TroupeMasterGrimmP",
        "GalienP",
        "GreyPrinceZoteP",
        "UumuuP",
        "Hornet2P",
        "SlyP"
    ],
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight",
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/low.json
{
    "categoryName": "Low%",
    "splitIds": [
        "VengefulSpirit",
        "EnterGreenpath",
        "FungalWastesEntry",
        "TransClaw",
        "DeepnestSpa",
        "TramPass",
        "DeepnestStation",
        "DreamNail",
        "WatcherChandelier",
        "BlackKnightTrans",
        "Lemm2",
        "LumaflyLantern",
        "CrystalHeart",
        "Uumuu",
        "BeastsDenTrapBench",
        "HegemolDreamer",
        "UnchainedHollowKnight"
    ],
    "endTriggeringAutosplit": false,
    "endingSplit": {
        "name": "Hollow Knight",
        "icon": "HollowKnightBoss"
    },
    "gameName": "Hollow Knight",
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/pure-snail.json
{
    "categoryName": "Pure Snail",
    "splitIds": [
        "VengefulSpirit",
        "EnterGreenpath",
        "GreenpathStation",
        "MothwingCloak",
        "NotchShrumalOgres",
        "MantisClaw",
        "SporeShroom",
        "BlueLake",
        "KingsStationStation",
        "BaldurShell",
        "GorgeousHusk",
        "Lemm2",
        "LumaflyLantern",
        "CrystalHeart",
        "IsmasTear",
        "ShapeOfUnn",
        "NotchFogCanyon",
        "PureSnail"
    ],
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/florist.json
{
    "categoryName": "Florist%",
    "splitIds": [
        "-KingsPass",
        "-FalseKnight",
        "VengefulSpirit",
        "-EnterGreenpath",
        "MothwingCloak",
        "-MegaMossCharger",
        "-FogCanyonEntry",
        "-QueensStationStation",
        "-NotchShrumalOgres",
        "MantisClaw",
        "MantisLords",
        "-FragileHeart",
        "-CityGateOpen",
        "-killedSoulTwister",
        "-SpellTwister",
        "DesolateDive",
        "-TollBenchCity",
        "-OnObtainSimpleKey",
        "GruzMother",
        "-ShamanStone",
        "-CrystalPeakEntry",
        "-CrystalGuardian1",
        "-SlyKey",
        "CrystalHeart",
        "DescendingDark",
        "DreamNail",
        "-RestingGroundsStation",
        "-ElegantKey",
        "BroodingMawlek",
        "-FogCanyonEntry",
        "-NotchFogCanyon",
        "ShadeSoul",
        "-Lemm2",
        "-DungDefender",
        "-IsmasTear",
        "KingsBrand",
        "-KingsStationStation",
        "-Ore1",
        "-TollBenchBasin",
        "-OnObtainSimpleKey",
        "MonarchWings",
        "ShadeCloak",
        "-HiddenStationStation",
        "QueensGardensEntry",
        "-EnterDeepnest",
        "Nosk",
        "-QueensGardensFrogsTrans",
        "-Marmu",
        "TraitorLord",
        "-NailUpgrade2",
        "-ColosseumBronze",
        "ColosseumSilver",
        "Xero",
        "Gorb",
        "-Ore3",
        "-Flukemarm",
        "NailUpgrade3",
        "-VengeflyKingP",
        "-GruzMotherP",
        "-FalseKnightP",
        "-MassiveMossChargerP",
        "-Hornet1P",
        "-GorbP",
        "-DungDefenderP",
        "-SoulWarriorP",
        "-BroodingMawlekP",
        "-OroMatoNailBrosP",
        "Pantheon1",
        "-XeroP",
        "-CrystalGuardianP",
        "-SoulMasterP",
        "-OblobblesP",
        "-MantisLordsP",
        "-MarmuP",
        "-NoskP",
        "-FlukemarmP",
        "-BrokenVesselP",
        "-SheoPaintmasterP",
        "Pantheon2",
        "-ElderbugFlower",
        "-givenOroFlower",
        "-FlowerQuest",
        "-givenWhiteLadyFlower",
        "-givenEmilitiaFlower",
        "givenGodseekerFlower"
    ],
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/fc-as-te.json
{
    "categoryName": "Forgotten Corners AS TE",
    "splitIds": [
        "CrystalHeart",
        "VengefulSpirit",
        "MothwingCloak",
        "IsmasTear",
        "MantisClaw",
        "DreamNail",
        "MonarchWings",
        "GalienEssence",
        "Hegemol",
        "ShamanStone",
        "DesolateDive",
        "DreamGate",
        "DescendingDark",
        "DashSlash",
        "Lurien",
        "ShadeCloak",
        "LoveKey",
        "Monomon",
        "KingsBrand",
        "CycloneSlash",
        "ShadeSoul",
        "GreatSlash",
        "DreamNail2",
        "HowlingWraiths",
        "AbyssShriek",
        "VoidHeart",
        "HollowKnightDreamnail"
    ],
    "endTriggeringAutosplit": false,
    "endingSplit": {
        "name": "Radiance",
        "icon": "RadianceBoss"
    },
    "gameName": "Hollow Knight Mods",
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/low-te-dropless.json
{
    "categoryName": "Low% True Ending Dropless",
    "splitIds": [
        "-CrossroadsStation",
        "VengefulSpirit",
        "-EnterGreenpath",
        "MothwingCloak",
        "MantisClaw",
        "-DeepnestSpa",
        "TramPass",
        "-HiddenStationStation",
        "-KingsStationStation",
        "-DreamNail",
        "SlyRescued",
        "-TreeWaterways",
        "-WatcherChandelier",
        "-BlackKnight",
        "Lurien",
        "-Lemm2",
        "-EnterSanctum",
        "-SoulMaster",
        "SoulTyrantEssence",
        "-TreeCity",
        "-LumaflyLantern",
        "CrystalHeart",
        "-EnterHornet2",
        "KingsBrand",
        "-TreeKingdomsEdge",
        "-BenchRGStag",
        "-BrokenVessel",
        "LostKinEssence",
        "-DreamWielder",
        "FailedChampionEssence",
        "-DreamGate",
        "ShadeCloak",
        "MarkothEssence",
        "-OnObtainGhostGravedigger",
        "-TreeCrossroads",
        "-TreeMound",
        "-TreeLegEater",
        "-UumuuEncountered",
        "Monomon",
        "-QueensGardensEntry",
        "-TreeQueensGardens",
        "-QueensGardensPostArenaTransition",
        "WhiteFragmentLeft",
        "-TreeDeepnest",
        "GalienEssence",
        "-BeastsDenTrapBench",
        "Hegemol",
        "-DreamNail2",
        "-Kingsoul",
        "VoidHeart",
        "-HollowKnightDreamnail"
    ],
    "endTriggeringAutosplit": false,
    "endingSplit": {
        "name": "Radiance",
        "icon": "RadianceBoss"
    },
    "gameName": "Hollow Knight Category Extensions",
    "variables": {
        "True Ending Glitch": "1.4.3.2+ NMG"
    },
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/sbcmo.json
{
    "categoryName": "Salubra's Blessing% CMO",
    "splitIds": [
        "WaywardCompass",
        "GatheringSwarm",
        "StalwartShell",
        "SoulCatcher",
        "ShamanStone",
        "SoulEater",
        "Dashmaster",
        "Sprintmaster",
        "Grubsong",
        "GrubberflysElegy",
        "FragileHeart",
        "FragileGreed",
        "FragileStrength",
        "SpellTwister",
        "SteadyBody",
        "HeavyBlow",
        "QuickSlash",
        "Longnail",
        "MarkOfPride",
        "FuryOfTheFallen",
        "ThornsOfAgony",
        "BaldurShell",
        "Flukenest",
        "DefendersCrest",
        "GlowingWomb",
        "QuickFocus",
        "DeepFocus",
        "LifebloodHeart",
        "LifebloodCore",
        "JonisBlessing",
        "Hiveblood",
        "SporeShroom",
        "SharpShadow",
        "ShapeOfUnn",
        "NailmastersGlory",
        "Weaversong",
        "DreamWielder",
        "Dreamshield",
        "Grimmchild",
        "Kingsoul",
        "SalubrasBlessing"
    ],
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "pauseOnMainMenu": true
}
