=== slaurent22/hk-split-maker/src/schema/hollowknight/splits.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://hksplitmaker.com/hollowknight/splits.schema.json",
    "title": "HK Splits",
    "description": "A Hollow Knight LiveSplit Configuration",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "names": {
            "additionalProperties": false,
            "description": "Name overrides for the splits. Map each autosplit id to a string or an array of strings.",
            "type": "object",
            "properties": {}
        },
        "icons": {
            "additionalProperties": false,
            "description": "Icon overrides for the splits. Map each autosplit id to a autosplit id or an array of autosplit ids.",
            "type": "object",
            "properties": {}
        },
        "ordered": {
            "description": "Ordered splits improve performance and are required for certain splits (e.g. KingsPass).",
            "type": "boolean"
        },
        "endTriggeringAutosplit": {
            "description": "Whether to end time at the last autosplit. Set this to false for full-game runs, where time ends on a final cutscene.",
            "type": "boolean"
        },
        "startTriggeringAutosplit": {
            "description": "Autosplit to use to start the timer, rather than starting on new file",
            "enum": []
        },
        "endingSplit": {
            "description": "Info for the last split if it's a game-ending split rather than an autosplit",
            "type": "object",
            "properties": {
                "name": "The name to appear in the LiveSplit UI",
                "icon": "The autosplit name whose icon to use (e.g. RadianceBoss, HollowKnightBoss)"
            }
        },
        "categoryName": {
            "description": "The category name on the associated speedrun.com board.",
            "type": "string"
        },
        "gameName": {
            "description": "The game name on the associated speedrun.com board.",
            "enum": [
                "Hollow Knight",
                "Hollow Knight Category Extensions",
                "Hollow Knight Mods"
            ]
        },
        "variables": {
            "description": "Additional Info",
            "type": "object"
        },
        "pauseOnMainMenu": {
            "description": "Pause on Main Menu (Required false for All Glitches)",
            "type": "boolean"
        },
        "splitIds": {
            "type": "array",
            "items": {
                "oneOf": []
            }
        },
        "offset": {
            "description": "When time should start (formatted like 00:00:00 or 00:00:00.0000000)",
            "type": "string"
        }
    },
    "required": [
        "endTriggeringAutosplit",
        "categoryName",
        "gameName",
        "splitIds"
    ]
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/lbc.json
{
    "categoryName": "Lifeblood Core%",
    "splitIds": [
        "VengefulSpirit",
        "EnterGreenpath",
        "MothwingCloak",
        "MantisClaw",
        "BlueLake",
        "GorgeousHusk",
        "JonisBlessing",
        "KingsBrand",
        "LifebloodCore"
    ],
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/spelless-low.json
{
    "categoryName": "Low% Spelless",
    "splitIds": [
        "GruzMother",
        "Mask1",
        "DreamNail",
        "MantisClaw",
        "Hegemol",
        "BlackKnight",
        "Lurien",
        "CrystalHeart",
        "Uumuu",
        "Monomon"
    ],
    "endTriggeringAutosplit": false,
    "endingSplit": {
        "name": "Hollow Knight",
        "icon": "HollowKnightBoss"
    },
    "gameName": "Hollow Knight Category Extensions",
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/enraged-guardian.json
{
    "categoryName": "Enraged Guardian%",
    "splitIds": [
        "VengefulSpirit",
        "EnterGreenpath",
        "MothwingCloak",
        "MantisClaw",
        "BlueLake",
        "GorgeousHusk",
        "LumaflyLantern",
        "CrystalGuardian1",
        "CrystalGuardian2"
    ],
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/shriek.json
{
    "categoryName": "Shriek%",
    "splitIds": [
        "VengefulSpirit",
        "EnterGreenpath",
        "MothwingCloak",
        "MantisClaw",
        "HowlingWraiths",
        "BlueLake",
        "KingdomsEdgeEntry",
        "KingsBrand",
        "BasinEntry",
        "AbyssShriek"
    ],
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/clawless-shade-cloak.json
{
    "categoryName": "Clawless Shade Cloak",
    "splitIds": [
        "VengefulSpirit",
        "EnterGreenpath",
        "MothwingCloak",
        "KingdomsEdgeEntry",
        "EnterHornet2",
        "KingsBrand",
        "ShadeCloak"
    ],
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/low-ag.json
{
    "categoryName": "Low%",
    "splitIds": [
        "KingsPass",
        "FogCanyonEntry",
        "Dreamer1",
        "Dreamer2",
        "Dreamer3",
        "UnchainedHollowKnight"
    ],
    "endTriggeringAutosplit": false,
    "endingSplit": {
        "name": "Hollow Knight",
        "icon": "HollowKnightBoss"
    },
    "gameName": "Hollow Knight",
    "variables": {
        "Low% Glitch": "All Glitches"
    },
    "pauseOnMainMenu": false
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/spelless-dreamshield.json
{
    "categoryName": "Spelless",
    "splitIds": [
        "SlyRescued",
        "FalseKnight",
        "LumaflyLantern",
        "Dreamshield",
        "EnterGreenpath",
        "MothwingCloak",
        "MegaMossCharger",
        "FragileStrength",
        "MantisClaw",
        "CrystalHeart",
        "GorgeousHusk",
        "NailUpgrade1",
        "BlackKnight",
        "FogCanyonEntry",
        "Uumuu",
        "SporeShroom",
        "BeastsDenTrapBench",
        "Hegemol"
    ],
    "endTriggeringAutosplit": false,
    "endingSplit": {
        "name": "Hollow Knight",
        "icon": "HollowKnightBoss"
    },
    "gameName": "Hollow Knight Category Extensions",
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/5-mimics.json
{
    "categoryName": "5 Mimics",
    "splitIds": [
        "VengefulSpirit",
        "EnterGreenpath",
        "MothwingCloak",
        "MantisClaw",
        "Mimic3",
        "BlueLake",
        "Lemm2",
        "CrystalHeart",
        "Mimic4",
        "LittleFool",
        "ColosseumBronze",
        "Mimic5"
    ],
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "pauseOnMainMenu": true
}
