=== slaurent22/hk-split-maker/src/schema/hollowknight/splits.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://hksplitmaker.com/hollowknight/splits.schema.json",
    "title": "HK Splits",
    "description": "A Hollow Knight LiveSplit Configuration",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "names": {
            "additionalProperties": false,
            "description": "Name overrides for the splits. Map each autosplit id to a string or an array of strings.",
            "type": "object",
            "properties": {}
        },
        "icons": {
            "additionalProperties": false,
            "description": "Icon overrides for the splits. Map each autosplit id to a autosplit id or an array of autosplit ids.",
            "type": "object",
            "properties": {}
        },
        "ordered": {
            "description": "Ordered splits improve performance and are required for certain splits (e.g. KingsPass).",
            "type": "boolean"
        },
        "endTriggeringAutosplit": {
            "description": "Whether to end time at the last autosplit. Set this to false for full-game runs, where time ends on a final cutscene.",
            "type": "boolean"
        },
        "startTriggeringAutosplit": {
            "description": "Autosplit to use to start the timer, rather than starting on new file",
            "enum": []
        },
        "endingSplit": {
            "description": "Info for the last split if it's a game-ending split rather than an autosplit",
            "type": "object",
            "properties": {
                "name": "The name to appear in the LiveSplit UI",
                "icon": "The autosplit name whose icon to use (e.g. RadianceBoss, HollowKnightBoss)"
            }
        },
        "categoryName": {
            "description": "The category name on the associated speedrun.com board.",
            "type": "string"
        },
        "gameName": {
            "description": "The game name on the associated speedrun.com board.",
            "enum": [
                "Hollow Knight",
                "Hollow Knight Category Extensions",
                "Hollow Knight Mods"
            ]
        },
        "variables": {
            "description": "Additional Info",
            "type": "object"
        },
        "pauseOnMainMenu": {
            "description": "Pause on Main Menu (Required false for All Glitches)",
            "type": "boolean"
        },
        "splitIds": {
            "type": "array",
            "items": {
                "oneOf": []
            }
        },
        "offset": {
            "description": "When time should start (formatted like 00:00:00 or 00:00:00.0000000)",
            "type": "string"
        }
    },
    "required": [
        "endTriggeringAutosplit",
        "categoryName",
        "gameName",
        "splitIds"
    ]
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/nice-1221.json
{
    "categoryName": "Nice%",
    "splitIds": [
        "FuryOfTheFallen",
        "VengefulSpirit",
        "SoulCatcher",
        "MothwingCloak",
        "MantisClaw",
        "MantisLords",
        "MarkOfPride",
        "Dashmaster",
        "GruzMother",
        "ShamanStone",
        "DashSlash",
        "ShadeSoul",
        "SpellTwister",
        "DesolateDive",
        "CrystalHeart",
        "DescendingDark",
        "DreamNail",
        "Dreamshield",
        "Lurien",
        "Flukenest",
        "DefendersCrest",
        "IsmasTear",
        "MonarchWings",
        "KingsBrand",
        "CycloneSlash",
        "Gorb",
        "JonisBlessing",
        "BaldurShell",
        "GreatSlash",
        "ThornsOfAgony",
        "NailmastersGlory",
        "WaywardCompass",
        "Grubsong",
        "Mask1",
        "FragileStrength",
        "ElderHu",
        "Monomon",
        "HowlingWraiths",
        "Hegemol",
        "Xero",
        "SoulEater",
        "QuickFocus",
        "ShadeCloak",
        "AbyssShriek"
    ],
    "endTriggeringAutosplit": false,
    "endingSplit": {
        "name": "Hollow Knight",
        "icon": "HollowKnightBoss"
    },
    "gameName": "Hollow Knight Category Extensions",
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/all-whispering-roots.json
{
    "categoryName": "All Whispering Roots",
    "splitIds": [
        "VengefulSpirit",
        "EnterGreenpath",
        "MothwingCloak",
        "DreamNail",
        "MantisClaw",
        "TreeMantisVillage",
        "TreeRestingGrounds",
        "TreeWaterways",
        "TreeCity",
        "LumaflyLantern",
        "TreePeak",
        "CrystalHeart",
        "TreeCliffs",
        "TreeCrossroads",
        "TreeMound",
        "TreeLegEater",
        "TreeGlade",
        "TreeQueensGardens",
        "TreeGreenpath",
        "TreeDeepnest",
        "TreeHive",
        "TreeKingdomsEdge"
    ],
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/3vf-stag-nest.json
{
    "categoryName": "3 Vessel Fragments",
    "splitIds": [
        "VengefulSpirit",
        "EnterGreenpath",
        "MothwingCloak",
        "MantisClaw",
        "VesselFragment1",
        "VesselFragment2",
        "Vessel1"
    ],
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/spelless.json
{
    "categoryName": "Spelless",
    "splitIds": [
        "FuryOfTheFallen",
        "FalseKnight",
        "Longnail",
        "EnterGreenpath",
        "MothwingCloak",
        "MegaMossCharger",
        "FragileStrength",
        "MantisClaw",
        "DreamNail",
        "GorgeousHusk",
        "NailUpgrade1",
        "BlackKnight",
        "LumaflyLantern",
        "CrystalHeart",
        "Uumuu",
        "SporeShroom",
        "BeastsDenTrapBench",
        "Hegemol"
    ],
    "endTriggeringAutosplit": false,
    "endingSplit": {
        "name": "Hollow Knight",
        "icon": "HollowKnightBoss"
    },
    "gameName": "Hollow Knight Category Extensions",
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/te-flukamoth.json
{
    "categoryName": "True Ending",
    "splitIds": [
        "FuryOfTheFallen",
        "VengefulSpirit",
        "SoulCatcher",
        "MothwingCloak",
        "NotchShrumalOgres",
        "TransClaw",
        "Lemm2",
        "SpellTwister",
        "DesolateDive",
        "StoreroomsStation",
        "SlyKey",
        "CrystalHeart",
        "DreamNail",
        "Dreamshield",
        "NotchSalubra1",
        "ElegantKey",
        "EnterSanctumWithShadeSoul",
        "SoulTyrantEssence",
        "Flukenest",
        "BrokenVessel",
        "LostKinEssence",
        "FailedChampionEssence",
        "DreamGate",
        "KingsStationStation",
        "KingsBrand",
        "ShadeCloak",
        "Markoth",
        "Lurien",
        "LumaflyLantern",
        "Monomon",
        "NoEyesEssence",
        "TollBenchQG",
        "MarmuEssence",
        "WhiteFragmentLeft",
        "GalienEssence",
        "Hegemol",
        "WhitePalaceEntry",
        "Kingsoul",
        "VoidHeart",
        "HollowKnightDreamnail"
    ],
    "endTriggeringAutosplit": false,
    "endingSplit": {
        "name": "Radiance",
        "icon": "RadianceBoss"
    },
    "gameName": "Hollow Knight",
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/all-unbreakable-charms.json
{
    "categoryName": "All Unbreakable Charms",
    "splitIds": [
        "VengefulSpirit",
        "MothwingCloak",
        "MantisClaw",
        "MantisLords",
        "GruzMother",
        "DreamNail",
        "FragileStrength",
        "GorbEssence",
        "XeroEssence",
        "KingdomsEdgeEntry",
        "KingsStationStation",
        "GorgeousHusk",
        "BlackKnight",
        "Lemm2",
        "AllUnbreakables"
    ],
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/p4.json
{
    "categoryName": "Pantheon of the Knight",
    "splitIds": [
        "EnragedGuardianP",
        "LostKinP",
        "NoEyesP",
        "TraitorLordP",
        "WhiteDefenderP",
        "FailedChampionP",
        "MarkothP",
        "WatcherKnightsP",
        "SoulTyrantP",
        "PureVesselP"
    ],
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight",
    "pauseOnMainMenu": true
}

=== slaurent22/hk-split-maker/src/asset/hollowknight/categories/egg.json
{
    "categoryName": "Egg",
    "splitIds": [
        "OnObtainRancidEgg",
        "OnObtainRancidEgg",
        "OnObtainRancidEgg",
        "OnObtainRancidEgg",
        "OnObtainRancidEgg",
        "OnObtainRancidEgg",
        "OnObtainRancidEgg",
        "OnObtainRancidEgg",
        "OnObtainRancidEgg",
        "OnObtainRancidEgg",
        "OnObtainRancidEgg",
        "OnObtainRancidEgg",
        "OnObtainRancidEgg",
        "OnObtainRancidEgg",
        "OnObtainRancidEgg",
        "OnObtainRancidEgg",
        "OnObtainRancidEgg",
        "OnObtainRancidEgg",
        "OnObtainRancidEgg",
        "OnObtainRancidEgg",
        "OnObtainRancidEgg"
    ],
    "endTriggeringAutosplit": true,
    "gameName": "Hollow Knight Category Extensions",
    "pauseOnMainMenu": true
}
